repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json, json5]
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        files: ^(pyproject\.toml|poetry\.lock)$
default_language_version:
  python: python3
minimum_pre_commit_version: 4.0.1
