name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting your idea! It helps make BookWith better.

  - type: textarea
    attributes:
      label: What feature would you like to see?
      description: Please describe what you'd like to happen.
    validations:
      required: true
