name: Backend CI

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'apps/api/**'

defaults:
  run:
    working-directory: apps/api

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: mypy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
          cache: poetry

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 'latest'

      - name: Install dependencies
        run: poetry install

      - name: Run mypy
        run: poetry run mypy src tests --explicit-package-bases

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
