---
name: Backend Minimal CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint & Format with Ruff
        run: poetry run ruff check .

      - name: Type check with MyPy
        run: poetry run mypy src --explicit-package-bases

      - name: Run tests (if any)
        if: ${{ hashFiles('tests/**') != '' }}
        run: poetry run pytest
